name: Build Dolphin Android

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code et des sous-modules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configuration de Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Installation du NDK
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "ndk;28.0.13004108"

      - name: Configuration de Gradle & Cache
        uses: gradle/actions/setup-gradle@v3

      - name: Compilation de l'APK
        working-directory: Source/Android
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease --stacktrace

      - name: Exportation du fichier APK
        uses: actions/upload-artifact@v4
        with:
          name: Dolphin-Android-APK
          path: Source/Android/app/build/outputs/apk/release/*.apk
